//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicaEdenred.wcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filters", Namespace="http://schemas.datacontract.org/2004/07/wcfEdenred.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Filters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage {
            get {
                return this.RowsPerPageField;
            }
            set {
                if ((this.RowsPerPageField.Equals(value) != true)) {
                    this.RowsPerPageField = value;
                    this.RaisePropertyChanged("RowsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaBE", Namespace="http://schemas.datacontract.org/2004/07/wcfEdenred.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class FacturaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_facturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((this.fecha_creacionField.Equals(value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_factura {
            get {
                return this.id_facturaField;
            }
            set {
                if ((this.id_facturaField.Equals(value) != true)) {
                    this.id_facturaField = value;
                    this.RaisePropertyChanged("id_factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDetalleBE", Namespace="http://schemas.datacontract.org/2004/07/wcfEdenred.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class FacturaDetalleBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_articuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalle_articuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_facturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_facturaDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precio_ventaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_articulo {
            get {
                return this.cod_articuloField;
            }
            set {
                if ((this.cod_articuloField.Equals(value) != true)) {
                    this.cod_articuloField = value;
                    this.RaisePropertyChanged("cod_articulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalle_articulo {
            get {
                return this.detalle_articuloField;
            }
            set {
                if ((object.ReferenceEquals(this.detalle_articuloField, value) != true)) {
                    this.detalle_articuloField = value;
                    this.RaisePropertyChanged("detalle_articulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((this.fecha_creacionField.Equals(value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_factura {
            get {
                return this.id_facturaField;
            }
            set {
                if ((this.id_facturaField.Equals(value) != true)) {
                    this.id_facturaField = value;
                    this.RaisePropertyChanged("id_factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_facturaDetalle {
            get {
                return this.id_facturaDetalleField;
            }
            set {
                if ((this.id_facturaDetalleField.Equals(value) != true)) {
                    this.id_facturaDetalleField = value;
                    this.RaisePropertyChanged("id_facturaDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio_venta {
            get {
                return this.precio_ventaField;
            }
            set {
                if ((this.precio_ventaField.Equals(value) != true)) {
                    this.precio_ventaField = value;
                    this.RaisePropertyChanged("precio_venta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInvoiceList", ReplyAction="http://tempuri.org/IService1/getInvoiceListResponse")]
        System.Collections.Generic.List<practicaEdenred.wcfService.FacturaBE> getInvoiceList(practicaEdenred.wcfService.Filters filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInvoiceList", ReplyAction="http://tempuri.org/IService1/getInvoiceListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<practicaEdenred.wcfService.FacturaBE>> getInvoiceListAsync(practicaEdenred.wcfService.Filters filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInvoiceById", ReplyAction="http://tempuri.org/IService1/getInvoiceByIdResponse")]
        System.Collections.Generic.List<practicaEdenred.wcfService.FacturaDetalleBE> getInvoiceById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInvoiceById", ReplyAction="http://tempuri.org/IService1/getInvoiceByIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<practicaEdenred.wcfService.FacturaDetalleBE>> getInvoiceByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : practicaEdenred.wcfService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<practicaEdenred.wcfService.IService1>, practicaEdenred.wcfService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<practicaEdenred.wcfService.FacturaBE> getInvoiceList(practicaEdenred.wcfService.Filters filters) {
            return base.Channel.getInvoiceList(filters);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<practicaEdenred.wcfService.FacturaBE>> getInvoiceListAsync(practicaEdenred.wcfService.Filters filters) {
            return base.Channel.getInvoiceListAsync(filters);
        }
        
        public System.Collections.Generic.List<practicaEdenred.wcfService.FacturaDetalleBE> getInvoiceById(int Id) {
            return base.Channel.getInvoiceById(Id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<practicaEdenred.wcfService.FacturaDetalleBE>> getInvoiceByIdAsync(int Id) {
            return base.Channel.getInvoiceByIdAsync(Id);
        }
    }
}
